server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

logging:
  file: log/@project.artifactId@.log

spring:
  application:
    name: @project.artifactId@
  zipkin:
    enabled: false
---
spring:
  profiles: docker
  zipkin:
    enabled: true
    base-url: http://zipkin:9411/
