server:
  port: 7070

spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    chat-message:
      path: /chat-message/**
      serviceId: chat-message-service
    account:
      path: /auth/**
      serviceId: auth-service
#  prefix: /api
