server:
  port: 7070

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
zuul:
  routes:
    chat-message:
      path: /chat/**
      sensitiveHeaders:
      serviceId: chat-message-service
    account:
      path: /auth/**
      sensitiveHeaders:
      serviceId: auth-service
#  prefix: /api

logging:
  file: log/@project.artifactId@.log
  level:
    org.springframework.web: DEBUG

spring:
  application:
    name: @project.artifactId@
  zipkin:
    enabled: false
---
spring:
  profiles: docker
  zipkin:
    enabled: true
    base-url: http://zipkin:9411/