server:
  port: 8080

spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    chat-message:
      path: /chat/**
      sensitiveHeaders:
      serviceId: chat-message-service
    account:
      path: /auth/**
      sensitiveHeaders:
      serviceId: auth-service
#  prefix: /api
