version: '3'
services:
  service-register-center:
    image: longma-site/service-register-center:1.0-SNAPSHOT
    ports:
      - "8761:8761"
    depends_on:
      - logstash

  gateway:
    image: longma-site/gateway:1.0-SNAPSHOT
    ports:
      - "7070:7070"
    environment:
      EUREKA_HOST: service-register-center
    depends_on:
      - service-register-center

  auth-service:
    image: longma-site/auth-service:1.0-SNAPSHOT
    ports:
      - "8000"
    environment:
      EUREKA_HOST: service-register-center
    depends_on:
      - service-register-center

  chat-message-service:
    image: longma-site/chat-message-service:1.0-SNAPSHOT
    ports:
      - "8010"
    environment:
      EUREKA_HOST: service-register-center
    depends_on:
      - service-register-center

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - longma

  logstash:
    image: docker.elastic.co/logstash/logstash:5.5.2
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - longma

  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - longma

networks:
  longma:
    driver: bridge
