server:
  port: 8080

spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    chat-message:
      path: /chat-message/**
      serviceId: chat-message-service
    account:
      path: /account/**
      serviceId: account-service
