server:
  port: 8081

spring:
  application:
    name: @project.artifactId@

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

feign:
  hystrix:
    enabled: false
