server:
  port: 8010
#  context-path: /chat-message

spring:
  application:
    name: chat-message-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

security:
  oauth2:
#    client:
#      client-id: acme
#      client-secret: acmesecret
#      access-token-uri: http://localhost:8000/oauth/token
#      user-authorization-uri: http://localhost:8000/oauth/authorize
    resource:
      loadBalanced: true
      user-info-uri: http://auth-service/me

logging:
  level:
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG
  file: log/@project.artifactId@.log