server:
  port: 9090
  context-path: /chat-message

spring:
  application:
    name: chat-message-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      user-info-uri: http://localhost:8080/me

#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG