server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

logging:
  file: log/@project.artifactId@.log
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG

spring:
  application:
    name: @project.artifactId@
  zipkin:
    enabled: false
---
spring:
  profiles: docker
  zipkin:
    enabled: true
    base-url: http://zipkin:9411/